name: socket_io_common
description: Socket.io common parser library.
version: 0.9.1
author: jumperchen <jumperchen@potix.com>
homepage: https://www.zkoss.org
repository: https://github.com/rikulo/socket_io_common
issue_tracker: https://github.com/rikulo/socket_io_common/issues

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: '^0.11.3+2'

dev_dependencies:
  test: ^1.0.0
